repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.9.0
  hooks:
    - id: pyupgrade
      args:
        - --keep-runtime-typing
        - --py39-plus

- repo: https://github.com/python-poetry/poetry
  rev: 1.5.1
  hooks:
    - id: poetry-check

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-yaml

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  -   id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.280"
  hooks:
  - id: ruff